# Generated by Django 5.2.15 on 2026-06-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
