# Generated by Django 5.2.15 on 2026-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_score',
            field=models.IntegerField(default=0),
        ),
    ]
