# Generated by Django 5.2.15 on 2026-06-09 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.pod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pod', 'user')},
            },
        ),
    ]
